from selenium import webdriver
import time
import unittest
from selenium.webdriver.support.select import Select
class Test_OA_1(unittest.TestCase):
    def setUp(self):
        self.wb=webdriver.Firefox()
        self.wb.get('http://192.168.0.121:808')
        time.sleep(5)
        self.wb.find_element_by_xpath('//*[@id="tbx_UserName"]').send_keys('adm')
        time.sleep(3)
        self.wb.find_element_by_xpath('//*[@id="tbx_Password"]').send_keys('adm')
        time.sleep(3)
        self.wb.find_element_by_id('ibtLogin').click()
        time.sleep(5)
        a = self.wb.find_element_by_xpath('/html/body/div[4]/div/div[1]/div[3]/ul/li/div[1]').text
        print('sjdf',a)
        self.assertEqual(a, '我的桌面', msg='登录失败')
    # 新建费用报销单
    def test_1(self):
        self.wb.find_element_by_css_selector('.tabmenu_content > div:nth-child(1) > ul:nth-child(6) > li:nth-child(1)').click()
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/div[2]/div/div[2]/div[1]/ul[3]/li[1]').click()
        time.sleep(3)
        self.wb.switch_to.frame(2)
        # Select(self.wb.find_element_by_id('kind')).select_by_value('009')
        self.wb.find_element_by_id('kind').click()
        # time.sleep(3)
        self.wb.find_element_by_xpath("/html/body/form/ul/li[1]/select/option[1]").click()
        time.sleep(3)
        self.wb.find_element_by_xpath('//*[@id="subject"]').send_keys('出差费用')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[1]/tbody/tr[2]/td[4]/input').send_keys('002020-06-03')
        time.sleep(5)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[1]/tbody/tr[2]/td[6]/input').send_keys("1")
        time.sleep(3)
        self.wb.find_element_by_xpath("/html/body/form/ol/li/table[2]/tbody/tr[2]/td[2]/input").send_keys('住宿')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[2]/td[3]/input').send_keys('260')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[3]/td[2]/input').send_keys('飞机票')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[3]/td[3]/input').send_keys('660')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[4]/td[2]/input').send_keys('伙食费')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[4]/td[3]/input').send_keys('800')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[6]/td[3]/input').send_keys('1720')
        time.sleep(3)
        # self.wb.find_element_by_xpath('//*[@id="upLocFile"]').send_keys('C:\\Users\\Administrator\\Desktop\\123.doc')
        # time.sleep(5)
        self.wb.find_element_by_xpath('//*[@id="save"]').click()
        self.a=self.wb.switch_to.alert
        b=self.a.text
        self.assertEqual(b,'成功：当前事务创建成功！',msg='成功：当前事务创建成功！')
        time.sleep(3)
        # self.a.accept()
    # 主题输入为空
    def test_2(self):
        self.wb.find_element_by_css_selector('.tabmenu_content > div:nth-child(1) > ul:nth-child(6) > li:nth-child(1)').click()
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/div[2]/div/div[2]/div[1]/ul[3]/li[1]').click()
        time.sleep(3)
        self.wb.switch_to.frame(2)
        # Select(self.wb.find_element_by_id('kind')).select_by_value('009')
        self.wb.find_element_by_id('kind').click()
        # time.sleep(3)
        self.wb.find_element_by_xpath("/html/body/form/ul/li[1]/select/option[1]").click()
        time.sleep(3)
        self.wb.find_element_by_xpath('//*[@id="subject"]').send_keys()
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[1]/tbody/tr[2]/td[4]/input').send_keys(
            '002020-06-03')
        time.sleep(5)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[1]/tbody/tr[2]/td[6]/input').send_keys("1")
        time.sleep(3)
        self.wb.find_element_by_xpath("/html/body/form/ol/li/table[2]/tbody/tr[2]/td[2]/input").send_keys('住宿')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[2]/td[3]/input').send_keys('260')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[3]/td[2]/input').send_keys('飞机票')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[3]/td[3]/input').send_keys('660')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[4]/td[2]/input').send_keys('伙食费')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[4]/td[3]/input').send_keys('800')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[6]/td[3]/input').send_keys('1720')
        time.sleep(3)
        # self.wb.find_element_by_xpath('//*[@id="upLocFile"]').send_keys('C:\\Users\\Administrator\\Desktop\\123.doc')
        # time.sleep(5)
        self.wb.find_element_by_xpath('//*[@id="save"]').click()
        a=self.wb.find_element_by_xpath('/html/body/div').text
        print("主题为空",a)
        self.assertEqual(a, '◆\n◆\n!请填写此字段。', msg='不能为空')
        time.sleep(3)
    #日期输入为空
    def test_3(self):
        self.wb.find_element_by_css_selector('.tabmenu_content > div:nth-child(1) > ul:nth-child(6) > li:nth-child(1)').click()
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/div[2]/div/div[2]/div[1]/ul[3]/li[1]').click()
        time.sleep(3)
        self.wb.switch_to.frame(2)
        # Select(self.wb.find_element_by_id('kind')).select_by_value('009')
        self.wb.find_element_by_id('kind').click()
        time.sleep(3)
        self.wb.find_element_by_xpath("/html/body/form/ul/li[1]/select/option[1]").click()
        time.sleep(3)
        self.wb.find_element_by_xpath('//*[@id="subject"]').send_keys('出差费用')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[1]/tbody/tr[2]/td[4]/input').send_keys()
        time.sleep(5)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[1]/tbody/tr[2]/td[6]/input').send_keys("1")
        time.sleep(3)
        self.wb.find_element_by_xpath("/html/body/form/ol/li/table[2]/tbody/tr[2]/td[2]/input").send_keys('住宿')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[2]/td[3]/input').send_keys('260')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[3]/td[2]/input').send_keys('飞机票')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[3]/td[3]/input').send_keys('660')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[4]/td[2]/input').send_keys('伙食费')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[4]/td[3]/input').send_keys('800')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[6]/td[3]/input').send_keys('1720')
        time.sleep(3)
        # self.wb.find_element_by_xpath('//*[@id="upLocFile"]').send_keys('C:\\Users\\Administrator\\Desktop\\123.doc')
        # time.sleep(5)
        self.wb.find_element_by_xpath('//*[@id="save"]').click()
        a=self.wb.find_element_by_xpath('/html/body/div').text
        print("日期为空",a)
        self.assertEqual(a, '◆\n◆\n!请填写此字段。', msg='不能为空')
        time.sleep(3)
        self.a.accept()
    #项目为空
    def test_4(self):
        self.wb.find_element_by_css_selector('.tabmenu_content > div:nth-child(1) > ul:nth-child(6) > li:nth-child(1)').click()
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/div[2]/div/div[2]/div[1]/ul[3]/li[1]').click()
        time.sleep(3)
        self.wb.switch_to.frame(2)
        # Select(self.wb.find_element_by_id('kind')).select_by_value('009')
        self.wb.find_element_by_id('kind').click()
        # time.sleep(3)
        self.wb.find_element_by_xpath("/html/body/form/ul/li[1]/select/option[1]").click()
        time.sleep(3)
        self.wb.find_element_by_xpath('//*[@id="subject"]').send_keys('出差费用')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[1]/tbody/tr[2]/td[4]/input').send_keys('002020-06-03')
        time.sleep(5)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[1]/tbody/tr[2]/td[6]/input').send_keys("1")
        time.sleep(3)
        self.wb.find_element_by_xpath("/html/body/form/ol/li/table[2]/tbody/tr[2]/td[2]/input").send_keys()
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[2]/td[3]/input').send_keys('260')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[3]/td[2]/input').send_keys('飞机票')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[3]/td[3]/input').send_keys('660')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[4]/td[2]/input').send_keys('伙食费')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[4]/td[3]/input').send_keys('800')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[6]/td[3]/input').send_keys('1720')
        time.sleep(3)
        # self.wb.find_element_by_xpath('//*[@id="upLocFile"]').send_keys('C:\\Users\\Administrator\\Desktop\\123.doc')
        # time.sleep(5)
        self.wb.find_element_by_xpath('//*[@id="save"]').click()
        a=self.wb.find_element_by_xpath('/html/body/div').text
        print("项目为空",a)
        self.assertEqual(a, '◆\n◆\n!请填写此字段。', msg='不能为空')
        time.sleep(3)
        self.a.accept()
    #金额为空
    def test_5(self):
        self.wb.find_element_by_css_selector('.tabmenu_content > div:nth-child(1) > ul:nth-child(6) > li:nth-child(1)').click()
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/div[2]/div/div[2]/div[1]/ul[3]/li[1]').click()
        time.sleep(3)
        self.wb.switch_to.frame(2)
        # Select(self.wb.find_element_by_id('kind')).select_by_value('009')
        self.wb.find_element_by_id('kind').click()
        # time.sleep(3)
        self.wb.find_element_by_xpath("/html/body/form/ul/li[1]/select/option[1]").click()
        time.sleep(3)
        self.wb.find_element_by_xpath('//*[@id="subject"]').send_keys('出差费用')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[1]/tbody/tr[2]/td[4]/input').send_keys(
            '002020-06-03')
        time.sleep(5)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[1]/tbody/tr[2]/td[6]/input').send_keys("1")
        time.sleep(3)
        self.wb.find_element_by_xpath("/html/body/form/ol/li/table[2]/tbody/tr[2]/td[2]/input").send_keys('住宿')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[2]/td[3]/input').send_keys()
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[3]/td[2]/input').send_keys('飞机票')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[3]/td[3]/input').send_keys('660')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[4]/td[2]/input').send_keys('伙食费')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[4]/td[3]/input').send_keys('800')
        time.sleep(3)
        self.wb.find_element_by_xpath('/html/body/form/ol/li/table[2]/tbody/tr[6]/td[3]/input').send_keys('1720')
        time.sleep(3)
        # self.wb.find_element_by_xpath('//*[@id="upLocFile"]').send_keys('C:\\Users\\Administrator\\Desktop\\123.doc')
        # time.sleep(5)
        self.wb.find_element_by_xpath('//*[@id="save"]').click()
        a=self.wb.find_element_by_xpath('/html/body/div').text
        print("金额为空",a)
        self.assertEqual(a, '◆\n◆\n!请填写此字段。', msg='不能为空')
        time.sleep(3)
        self.a.accept()

    def tearDown(self):
        self.wb.quit()
        # self.wb.close()

if __name__ == '__main__':
    unittest.main()